apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: matchcrawler
  namespace: attendance
  labels:
    app: matchcrawler
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: matchcrawler
            image: quay.io/jacob_moeller/matchcrawler:nodb
          restartPolicy: Never


